# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.srcs/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0.xci
# IP: The module: 'Virtex_rst_mig_7series_0_200M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_rst_mig_7series_0_200M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_rst_mig_7series_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_rst_mig_7series_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.srcs/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0.xci
# IP: The module: 'Virtex_rst_mig_7series_0_200M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_rst_mig_7series_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_rst_mig_7series_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/dolu/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_rst_mig_7series_0_200M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
