let directoryPath='/blobcontent/@@portalCd/rbg/resources/@@env';const availableCultures=new Set(["en-US","en-GB","fr-FR","fr-GB","de-DE","it-IT","es-ES"]);const blackListedURLsSet=new Set([]);const portalConfig=[{Key:"cvgenius.com/es",portalCd:"ges",isGES:true,isValidLongLoaderCase:false,isLite:true,defaultCountryCD:"ES",defaultCultureCd:"en-US",localizationFileName:"es-ES.json",cssBundleName:"ges-app",startPage:"/getting-started",startHTSPage:"/how-to-start",countriesToBeOnTop:["ES"]},{Key:"cvgenius.com/it",portalCd:"git",isGIT:true,isValidLongLoaderCase:false,isLite:true,defaultCountryCD:"IT",defaultCultureCd:"en-US",localizationFileName:"it-IT.json",cssBundleName:"git-app",startPage:"/getting-started",startHTSPage:"/how-to-start",countriesToBeOnTop:["IT"]},{Key:"cvgenius.com/de",portalCd:"gde",isGDE:true,isValidLongLoaderCase:false,isLite:true,defaultCountryCD:"DE",defaultCultureCd:"en-US",localizationFileName:"de-DE.json",cssBundleName:"gde-app",startPage:"/getting-started",startHTSPage:"/how-to-start",countriesToBeOnTop:["DE"]},{Key:"cvgenius.com/uk",portalCd:"cvg",isCVG:true,isValidLongLoaderCase:false,isLite:true,defaultCountryCD:"GB",defaultCultureCd:"en-GB",localizationFileName:"en-GB.json",cssBundleName:"cvg-app",startPage:"/getting-started",startHTSPage:"/how-to-start",countriesToBeOnTop:["GB","UK","IE"]},{Key:"cvgenius.com/fr",portalCd:"gfr",isGFR:true,isValidLongLoaderCase:false,isLite:true,defaultCountryCD:"FR",defaultCultureCd:"fr-FR",localizationFileName:"fr-FR.json",cssBundleName:"gfr-app",startPage:"/se-lancer",startHTSPage:"/comment-se-lancer",countriesToBeOnTop:["FR","IE"]},{Key:"cvgenius.com",portalCd:"cvg",isCVG:true,isValidLongLoaderCase:false,isLite:true,defaultCountryCD:"GB",defaultCultureCd:"en-GB",cssBundleName:"cvg-app",startPage:"/getting-started",startHTSPage:"/how-to-start",countriesToBeOnTop:["GB","UK","IE"]},{Key:"resumegenius.com",portalCd:"rgn",isRG:true,isValidLongLoaderCase:true,isLite:false,defaultCountryCD:"US",defaultCultureCd:"en-US",cssBundleName:"rgn-app",startPage:"/getting-started",startHTSPage:"/how-to-start",experimentJsUrl:"/ui-experimentation/rgn/test-BLDRSA.js",countriesToBeOnTop:["US","CA","GB","AU"]},{Key:"resumecompanion.com",portalCd:"rcp",isRC:true,isValidLongLoaderCase:true,isLite:false,defaultCountryCD:"US",defaultCultureCd:"en-US",cssBundleName:"rcp-app",startPage:"/getting-started",startHTSPage:"/how-to-start",countriesToBeOnTop:["US","CA","GB","AU"]}];function getPortalSettings(){const countryCD=getCountryCodeFromUrl();const parts=window.location.hostname.split('.');const domain=parts.slice(-2).join('.');let key=countryCD?`${domain}/${countryCD}`:domain;let portalSetting=portalConfig.find(e=>e.Key===key);if(!portalSetting&&domain.includes("cvgenius.com")){key=`${domain}/uk`;portalSetting=portalConfig.find(e=>e.Key===key);}
return portalSetting;}
function getCountryCodeFromUrl(){const rawURLPath=window.location.href.replace(/\/\//g,'/');const languageCodePattern=/\/([a-z]{2})\//;const segments=rawURLPath.match(languageCodePattern);return segments&&!isSegmentBlacklisted(segments[1].trim())?segments[1].trim():'';}
async function CheckIfResourceFilePresentForCulture(filePath){try{const response=await fetch(filePath);return response.status===200;}catch(error){return false;}}
function CheckIfCultureCDPresentInList(cultureCD){return availableCultures.has(cultureCD);}
function isSegmentBlacklisted(segment){return blackListedURLsSet.has(segment);}
function getCountryAndLanguageFromURL(){let language="";let country=getCountryCodeFromUrl();const rawURLPath=window.location.href.replace(/\/\//g,'/');const languageAndCountryCodePattern=/\/([a-z]{2})\/([a-z]{2})\//;const segments=rawURLPath.match(languageAndCountryCodePattern);if(segments&&segments.length===3&&!isSegmentBlacklisted(segments[2].trim())){language=segments[2].trim();}
return{country,language};}
async function getLiteCulture(){let portalSetting=getPortalSettings();if(portalSetting.isLite){const defaultCultureCd=portalSetting.defaultCultureCd;const userBrowserLanguages=navigator.languages;const cultureObj=getCountryAndLanguageFromURL();let liteObj={currentCultureCD:defaultCultureCd,countryCD:cultureObj.country,localizationFileName:portalSetting.localizationFileName,languageCD:"",};directoryPath=directoryPath.replace('@@portalCd',portalSetting.portalCd).replace('@@env',getEnvironment());if(cultureObj.country&&cultureObj.language){const countryCD=(portalSetting.defaultCountryCD&&portalSetting.defaultCountryCD.trim())!==cultureObj.country.toUpperCase()?portalSetting.defaultCountryCD.trim():cultureObj.country.toUpperCase();const cultureCD=`${cultureObj.language.toLowerCase()}-${countryCD}`;const fileName=`${cultureCD}.json`;const filePath=`${directoryPath}/${fileName}`;if(CheckIfCultureCDPresentInList(cultureCD)||(await CheckIfResourceFilePresentForCulture(filePath))){liteObj.currentCultureCD=cultureCD;liteObj.countryCD=cultureObj.country;liteObj.languageCD=cultureObj.language?.toLowerCase();liteObj.localizationFileName=fileName;}}else if(cultureObj.country&&!cultureObj.language){const fileName=liteObj.localizationFileName||`${defaultCultureCd}.json`;const filePath=`${directoryPath}/${fileName}`;if(CheckIfCultureCDPresentInList(defaultCultureCd)||(await CheckIfResourceFilePresentForCulture(filePath))){liteObj.currentCultureCD=defaultCultureCd;liteObj.countryCD=cultureObj.country;liteObj.languageCD=cultureObj.language?.toLowerCase();liteObj.localizationFileName=fileName;}}else if(userBrowserLanguages&&userBrowserLanguages.length>0){for(let i=0;i<userBrowserLanguages.length;i++){const cultureArr=userBrowserLanguages[i].split(';')[0];const fileName=`${cultureArr}.json`;const filePath=`${directoryPath}/${fileName}`;if(CheckIfCultureCDPresentInList(cultureArr)||(await CheckIfResourceFilePresentForCulture(filePath))){liteObj.currentCultureCD=cultureArr;let array=cultureArr.split('-');liteObj.countryCD=array[1];liteObj.languageCD=array[0]?.toLowerCase();liteObj.localizationFileName=fileName;break;}else{const browserLanguage=cultureArr.split('-')[0];const fileName=`${browserLanguage}.json`;const filePath=`${directoryPath}/${fileName}`;if(CheckIfCultureCDPresentInList(browserLanguage)||(await CheckIfResourceFilePresentForCulture(filePath))){liteObj.currentCultureCD=browserLanguage;liteObj.localizationFileName=fileName;break;}}}}
portalSetting={...portalSetting,...liteObj};}
else{let cultureObj={currentCultureCD:portalSetting.defaultCultureCd,defaultCountryCode:portalSetting.defaultCountryCD,languageCD:"",};portalSetting={...portalSetting,...cultureObj};}
return portalSetting;}
function handlePortalConfiguration(data){BLDR.cultureCD=data.currentCultureCD;BLDR.defaultCountryCode=data.defaultCountryCode;if(data.isLite){if(data.countryCD&&data.languageCD)
BLDR.CountryCultureSlugPrefix="/"+data.countryCD+"/"+data.languageCD;else
BLDR.CountryCultureSlugPrefix=data.countryCD?"/"+data.countryCD:""
BLDR.CountrySlug=data.countryCD;BLDR.IsLitePortalFlow=BLDR.isLite=data.isLite;BLDR.liteFlowCultureCD=data.currentCultureCD?data.currentCultureCD:data.defaultCultureCd;BLDR.CultureCD=BLDR.cultureCD.split("-")[0];BLDR.localizationFileName=data.localizationFileName;delete data.languageCD;}
BLDR.isRG=data.isRG;BLDR.isCVG=data.isCVG;BLDR.isRC=data.isRC;BLDR.isGFR=data.isGFR;BLDR.isGDE=data.isGDE;BLDR.isGIT=data.isGIT;BLDR.isGES=data.isGES;BLDR.isEUPortal=BLDR.isLite&&!BLDR.isCVG;delete data.defaultCountryCode;delete data.currentCultureCD;delete data.countryCD;BLDR.Portal=data;BLDR.countriesToBeOnTop=data.countriesToBeOnTop;}
function getEnvironment(){var environment=window.location.host.split('.')[0];switch(environment){case "perf":environment="reg";break;case "resumegenius":case "resumecompanion":case "cvgenius":environment="prod";break;case "local":environment="pseudo";break;}
return environment;}
window.initializeSettings=function(callback){getLiteCulture().then((data)=>{handlePortalConfiguration(data);callback();}).catch((error)=>{console.log("Rejected:",error);});};