# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Virtex/Virtex.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex || ORIG_REF_NAME==Virtex} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_mig_7series_0_0_2/Virtex_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_mig_7series_0_0 || ORIG_REF_NAME==Virtex_mig_7series_0_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_microblaze_0_0/Virtex_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_microblaze_0_0 || ORIG_REF_NAME==Virtex_microblaze_0_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_dlmb_v10_0/Virtex_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_dlmb_v10_0 || ORIG_REF_NAME==Virtex_dlmb_v10_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_ilmb_v10_0/Virtex_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_ilmb_v10_0 || ORIG_REF_NAME==Virtex_ilmb_v10_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_dlmb_bram_if_cntlr_0/Virtex_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Virtex_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_ilmb_bram_if_cntlr_0/Virtex_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Virtex_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_lmb_bram_0/Virtex_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_lmb_bram_0 || ORIG_REF_NAME==Virtex_lmb_bram_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_xbar_0/Virtex_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_xbar_0 || ORIG_REF_NAME==Virtex_xbar_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_microblaze_0_axi_periph_0/Virtex_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Virtex_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Virtex_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_microblaze_0_xlconcat_0/Virtex_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Virtex_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_mdm_1_0/Virtex_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_mdm_1_0 || ORIG_REF_NAME==Virtex_mdm_1_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_rst_mig_7series_0_200M_0/Virtex_rst_mig_7series_0_200M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_rst_mig_7series_0_200M_0 || ORIG_REF_NAME==Virtex_rst_mig_7series_0_200M_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_axi_gpio_0_0/Virtex_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_axi_gpio_0_0 || ORIG_REF_NAME==Virtex_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_axi_gpio_0_1/Virtex_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_axi_gpio_0_1 || ORIG_REF_NAME==Virtex_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_pc_4/Virtex_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_pc_4 || ORIG_REF_NAME==Virtex_auto_pc_4} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_us_0/Virtex_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_us_0 || ORIG_REF_NAME==Virtex_auto_us_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_us_1/Virtex_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_us_1 || ORIG_REF_NAME==Virtex_auto_us_1} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_us_2/Virtex_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_us_2 || ORIG_REF_NAME==Virtex_auto_us_2} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_ds_0/Virtex_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_ds_0 || ORIG_REF_NAME==Virtex_auto_ds_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_pc_0/Virtex_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_pc_0 || ORIG_REF_NAME==Virtex_auto_pc_0} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_ds_1/Virtex_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_ds_1 || ORIG_REF_NAME==Virtex_auto_ds_1} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_pc_1/Virtex_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_pc_1 || ORIG_REF_NAME==Virtex_auto_pc_1} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_ds_2/Virtex_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_ds_2 || ORIG_REF_NAME==Virtex_auto_ds_2} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_pc_2/Virtex_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_pc_2 || ORIG_REF_NAME==Virtex_auto_pc_2} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_ds_3/Virtex_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_ds_3 || ORIG_REF_NAME==Virtex_auto_ds_3} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_auto_pc_3/Virtex_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_auto_pc_3 || ORIG_REF_NAME==Virtex_auto_pc_3} -quiet] -quiet

# IP: bd/Virtex/ip/Virtex_axi_uartlite_0_0/Virtex_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Virtex_axi_uartlite_0_0 || ORIG_REF_NAME==Virtex_axi_uartlite_0_0} -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/Virtex_ooc.xdc
