# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.srcs/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0.xci
# IP: The module: 'Virtex_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.srcs/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0.xci
# IP: The module: 'Virtex_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Thesis/VC707test/VC707test.gen/sources_1/bd/Virtex/ip/Virtex_microblaze_0_axi_intc_0/Virtex_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Virtex_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
